# Generated by Django 5.1.2 on 2024-11-03 09:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ipo_app", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ipodetails",
            name="user",
        ),
    ]
